// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRNSMudApp.Data;

#nullable disable

namespace SRNSMudApp.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260819061846_RevertParentTagIdToNullable")]
partial class _20260819061846_RevertParentTagIdToNullable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.7.26381.103")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("AspNetRoles");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("ProviderKey")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
            {
                b.Property<byte[]>("CredentialId")
                    .HasMaxLength(1024)
                    .HasColumnType("varbinary(1024)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Data", "Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>.Data#IdentityPasskeyData", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<byte[]>("Aaguid");

                        b1.Property<byte[]>("AttestationObject")
                            .IsRequired();

                        b1.Property<byte[]>("ClientDataJson")
                            .IsRequired();

                        b1.Property<DateTimeOffset>("CreatedAt");

                        b1.Property<bool>("IsBackedUp");

                        b1.Property<bool>("IsBackupEligible");

                        b1.Property<bool>("IsUserVerified");

                        b1.Property<string>("Name");

                        b1.Property<byte[]>("PublicKey")
                            .IsRequired();

                        b1.Property<long>("SignCount");

                        b1.PrimitiveCollection<string>("Transports");

                        b1
                            .ToJson("Data")
                            .HasColumnType("nvarchar(max)");
                    });

                b.HasKey("CredentialId");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserPasskeys");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("RoleId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Name")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

        modelBuilder.Entity("SRNSMudApp.Data.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers");
            });

        modelBuilder.Entity("SRNSMudApp.Data.Invitation", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("ExpirationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("InvitationCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("InvitationSourceJson")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("InvitedByAdminId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<bool>("IsUsed")
                    .HasColumnType("bit");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("InvitedByAdminId");

                b.HasIndex("OwnerId");

                b.ToTable("Invitations");
            });

        modelBuilder.Entity("SRNSMudApp.Data.Item", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ItemKindJson")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("ParentItemId")
                    .HasColumnType("int");

                b.Property<int>("TaggingRequestEntityId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("OwnerId");

                b.HasIndex("ParentItemId");

                b.HasIndex("TaggingRequestEntityId");

                b.ToTable("Items");
            });

        modelBuilder.Entity("SRNSMudApp.Data.NotificationReadState", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<DateTimeOffset>("ReadAt")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("SourceId")
                    .HasColumnType("int");

                b.Property<string>("SourceType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("NotificationReadStates");
            });

        modelBuilder.Entity("SRNSMudApp.Data.PublicTradeOffer", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<int>("OfferedTagId")
                    .HasColumnType("int");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("RequiredAssetAmount")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("OfferedTagId");

                b.HasIndex("OwnerId");

                b.ToTable("PublicTradeOffers");
            });

        modelBuilder.Entity("SRNSMudApp.Data.RightAsset", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("Amount")
                    .HasColumnType("int");

                b.Property<string>("BurnStatusJson")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsBurned")
                    .HasColumnType("bit");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("TargetTagId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("OwnerId");

                b.HasIndex("TargetTagId");

                b.ToTable("RightAssets");
            });

        modelBuilder.Entity("SRNSMudApp.Data.Tag", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("CachedWeight")
                    .HasColumnType("int");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Embedding")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsSystem")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int?>("ParentTagId")
                    .HasColumnType("int");

                b.Property<int?>("TagId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ParentTagId");

                b.HasIndex("TagId");

                b.HasIndex("OwnerId", "Name")
                    .IsUnique();

                b.ToTable("Tags");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TagRelation", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("ItemId")
                    .HasColumnType("int");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Weight")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ItemId");

                b.HasIndex("OwnerId");

                b.HasIndex("TagId");

                b.ToTable("TagRelations");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TagRelationToTag", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.Property<int>("TargetTagId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Weight")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("OwnerId");

                b.HasIndex("TagId");

                b.HasIndex("TargetTagId");

                b.ToTable("TagRelationToTags");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TagWeightLedger", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("ConsumedRightAssetId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Delta")
                    .HasColumnType("int");

                b.Property<bool>("IsOwnerAction")
                    .HasColumnType("bit");

                b.Property<int>("NewWeight")
                    .HasColumnType("int");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("PreviousWeight")
                    .HasColumnType("int");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("SourceId")
                    .HasColumnType("int");

                b.Property<string>("SourceType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.Property<string>("TagNameSnapshot")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ConsumedRightAssetId");

                b.HasIndex("OwnerId");

                b.HasIndex("SourceId");

                b.HasIndex("TagId");

                b.ToTable("TagWeightLedgers");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TaggingRequestEntity", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("ConsumedRightAssetId")
                    .HasColumnType("int");

                b.Property<string>("ContractPayloadJson")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ContractType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("ProposedWeight")
                    .HasColumnType("int");

                b.Property<string>("RejectionInfoJson")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RequestItemId")
                    .HasColumnType("int");

                b.Property<int>("RequestType")
                    .HasColumnType("int");

                b.Property<int>("RequestedTagId")
                    .HasColumnType("int");

                b.Property<string>("RequesterUserId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("TagOwnerUserId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("TargetItemId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ConsumedRightAssetId");

                b.HasIndex("OwnerId");

                b.HasIndex("RequestItemId")
                    .IsUnique();

                b.HasIndex("RequestedTagId");

                b.HasIndex("TargetItemId");

                b.ToTable("TaggingRequestContracts");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TimelineEvent", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("FollowedTagId")
                    .HasColumnType("int");

                b.Property<int>("NewWeight")
                    .HasColumnType("int");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("PreviousWeight")
                    .HasColumnType("int");

                b.Property<string>("TimelineTargetJson")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("FollowedTagId");

                b.HasIndex("OwnerId");

                b.ToTable("TimelineEvents");
            });

        modelBuilder.Entity("SRNSMudApp.Data.UserTagFollow", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("OwnerId");

                b.HasIndex("TagId");

                b.ToTable("UserTagFollows");
            });

        modelBuilder.Entity("TagTaggingRequestEntity", b =>
            {
                b.Property<int>("TaggingRequestEntityId")
                    .HasColumnType("int");

                b.Property<int>("TagsId")
                    .HasColumnType("int");

                b.HasKey("TaggingRequestEntityId", "TagsId");

                b.HasIndex("TagsId");

                b.ToTable("TagTaggingRequestEntity");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("SRNSMudApp.Data.Invitation", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", "InvitedByAdmin")
                    .WithMany()
                    .HasForeignKey("InvitedByAdminId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("InvitedByAdmin");

                b.Navigation("Owner");
            });

        modelBuilder.Entity("SRNSMudApp.Data.Item", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Item", "ParentItem")
                    .WithMany("Replies")
                    .HasForeignKey("ParentItemId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.TaggingRequestEntity", "TaggingRequest")
                    .WithMany("Replies")
                    .HasForeignKey("TaggingRequestEntityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Owner");

                b.Navigation("ParentItem");

                b.Navigation("TaggingRequest");
            });

        modelBuilder.Entity("SRNSMudApp.Data.PublicTradeOffer", b =>
            {
                b.HasOne("SRNSMudApp.Data.Tag", "OfferedTag")
                    .WithMany()
                    .HasForeignKey("OfferedTagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("OfferedTag");

                b.Navigation("Owner");
            });

        modelBuilder.Entity("SRNSMudApp.Data.RightAsset", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", "TargetTag")
                    .WithMany()
                    .HasForeignKey("TargetTagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Owner");

                b.Navigation("TargetTag");
            });

        modelBuilder.Entity("SRNSMudApp.Data.Tag", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", "ParentTag")
                    .WithMany()
                    .HasForeignKey("ParentTagId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SRNSMudApp.Data.Tag", null)
                    .WithMany("Children")
                    .HasForeignKey("TagId");

                b.Navigation("Owner");

                b.Navigation("ParentTag");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TagRelation", b =>
            {
                b.HasOne("SRNSMudApp.Data.Item", "Item")
                    .WithMany("TagRelations")
                    .HasForeignKey("ItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", "Tag")
                    .WithMany("TagRelations")
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Item");

                b.Navigation("Owner");

                b.Navigation("Tag");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TagRelationToTag", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", "Tag")
                    .WithMany("SourceTagRelations")
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", "TargetTag")
                    .WithMany("TargetTagRelations")
                    .HasForeignKey("TargetTagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Owner");

                b.Navigation("Tag");

                b.Navigation("TargetTag");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TagWeightLedger", b =>
            {
                b.HasOne("SRNSMudApp.Data.RightAsset", "ConsumedRightAsset")
                    .WithMany()
                    .HasForeignKey("ConsumedRightAssetId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.TagRelation", "TagRelation")
                    .WithMany()
                    .HasForeignKey("SourceId")
                    .OnDelete(DeleteBehavior.SetNull)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", "Tag")
                    .WithMany("TagWeightLedgers")
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("ConsumedRightAsset");

                b.Navigation("Owner");

                b.Navigation("Tag");

                b.Navigation("TagRelation");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TaggingRequestEntity", b =>
            {
                b.HasOne("SRNSMudApp.Data.RightAsset", "ConsumedRightAsset")
                    .WithMany()
                    .HasForeignKey("ConsumedRightAssetId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Item", "RequestItem")
                    .WithOne("AsRequestOf")
                    .HasForeignKey("SRNSMudApp.Data.TaggingRequestEntity", "RequestItemId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", "RequestedTag")
                    .WithMany()
                    .HasForeignKey("RequestedTagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Item", "TargetItem")
                    .WithMany()
                    .HasForeignKey("TargetItemId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("ConsumedRightAsset");

                b.Navigation("Owner");

                b.Navigation("RequestItem");

                b.Navigation("RequestedTag");

                b.Navigation("TargetItem");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TimelineEvent", b =>
            {
                b.HasOne("SRNSMudApp.Data.Tag", "FollowedTag")
                    .WithMany()
                    .HasForeignKey("FollowedTagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("FollowedTag");

                b.Navigation("Owner");
            });

        modelBuilder.Entity("SRNSMudApp.Data.UserTagFollow", b =>
            {
                b.HasOne("SRNSMudApp.Data.ApplicationUser", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", "Tag")
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Owner");

                b.Navigation("Tag");
            });

        modelBuilder.Entity("TagTaggingRequestEntity", b =>
            {
                b.HasOne("SRNSMudApp.Data.TaggingRequestEntity", null)
                    .WithMany()
                    .HasForeignKey("TaggingRequestEntityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SRNSMudApp.Data.Tag", null)
                    .WithMany()
                    .HasForeignKey("TagsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("SRNSMudApp.Data.Item", b =>
            {
                b.Navigation("AsRequestOf")
                    .IsRequired();

                b.Navigation("Replies");

                b.Navigation("TagRelations");
            });

        modelBuilder.Entity("SRNSMudApp.Data.Tag", b =>
            {
                b.Navigation("Children");

                b.Navigation("SourceTagRelations");

                b.Navigation("TagRelations");

                b.Navigation("TagWeightLedgers");

                b.Navigation("TargetTagRelations");
            });

        modelBuilder.Entity("SRNSMudApp.Data.TaggingRequestEntity", b =>
            {
                b.Navigation("Replies");
            });
#pragma warning restore 612, 618
    }
}
